# NOT NULL ON CONFLICT REPLACE with a DEFAULT: a NULL insert takes the default. to_sql drops it.
CREATE TABLE t(id INTEGER PRIMARY KEY, n INTEGER NOT NULL ON CONFLICT REPLACE DEFAULT 7, b INTEGER)
INSERT INTO t(n, b) VALUES (1, 1)
UPDATE t SET b = b + 100
@reopen
INSERT INTO t(n, b) VALUES (NULL, 2)
SELECT * FROM t ORDER BY id
